image:
  - Visual Studio 2017
  - Visual Studio 2019

branches:
  only:
  - master

configuration: Release

platform:
  - x64

install:

-  ps: |

     if (![IO.File]::Exists("C:\ninja-1.8.2\ninja.exe")) {
       Start-FileDownload 'https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip'
       7z x -y ninja-win.zip -oC:\ninja-1.8.2
     }
     $env:PATH="C:\ninja-1.8.2;$env:PATH"

     if (![IO.File]::Exists("C:\cmake-3.17.0\bin\cmake.exe")) {
       Start-FileDownload 'https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0-win64-x64.zip'
       7z x -y cmake-3.17.0-win64-x64.zip -oC:\cmake-3.17.0 cmake-3.17.0-win64-x64\*.*
     }
     $env:PATH="C:\cmake-3.17.0\bin;$env:PATH"

-  for /f "tokens=1* delims=" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath') do call "%%i\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM:x86=x64_x86%
-  ninja --version
-  ls ..\..\cmake-3.17.0
-  pwd
-  cmd /c "C:\cmake-3.17.0\bin\cmake.exe" --version 

cache: 
  - C:\ninja-1.8.2
  - C:\cmake-3.17.0

build_script:
-  mkdir cmake-build
-  cd cmake-build
-  cmd /c "C:\cmake-3.17.0\bin\cmake.exe" .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
-  cmd /c "C:\cmake-3.17.0\bin\cmake.exe" --build . --target Project