language: cpp

os: linux
dist: xenial

services:
  - docker
env:
  - COMPILER='gcc'       IMAGE_NAME=vglad/centos8:gcc9
  - COMPILER='clang-8'   IMAGE_NAME=vglad/centos8:clang8

before_script:
  - docker pull ${IMAGE_NAME} || true
  - export PROJECT_NAME=ProjectTemplate
  - export PROJECT_DIR=/opt/dev/${PROJECT_NAME}
  - export BUILD_SCRIPT_NAME=build.sh

script:
  - docker run -t
      -e PROJECT_DIR=${PROJECT_DIR} -e COMPILER=${COMPILER}
      -v ${TRAVIS_BUILD_DIR}:${PROJECT_DIR}
      ${IMAGE_NAME} ${PROJECT_DIR}/${BUILD_SCRIPT_NAME}

notifications:
  email: false
